### PR TITLE
fix for doing auth on redis connection pools

### PR DESCRIPTION
**Pull request by taylorking**

### CODE REVIEW

**Comment by taylorking** [comment]
Before

before


After

after

**Comment by rmg** [comment]
Happy dance! 🎉

**Comment by taylorking** [comment]
props to @rmg

**Comment by mhamann** [comment]
Nice work!

**Comment by rmg** [comment]
With my commit pedant hat on....
```
Optimize redis connection pooling

Reduce redis queries/commands by as much as 2x by only authenticating
each connection once. If a connection pool is used then most of the
calls to redis will be done using connected sessions which have already
been authenticated.
```

**Comment by rmg** [comment]
damn, too slow 😞

**Pull request merged**
