### PR TITLE
Implement better routing for exact gatewaypath match

### PR DESCRIPTION
**Pull request by alexsong93**
@taylorking @gclyne PTAL
Now if there is an exact match, it uses that key from redis. Otherwise, it goes through the path param/proxy lookup algorithm.

### CODE REVIEW

**Comment by mhamann** [comment]
@alexsong93 could this result in 3 redis lookups per call in the case that an exact match is not found?

**Comment by alexsong93** [comment]
@mhamann Yes that is correct. It's a tradeoff of if we want fast processing for exact matches, but may have to make multiple calls if there isn't an exact match, or make just one call to redis every time, but have to loop through the resources and perform the lookup algorithm every time

**Comment by mhamann** [comment]
Would really be a total of two lookups, right? One for the index and one for the found doc...?

**Comment by alexsong93** [comment]
Ultimately, yes. I meant that compared to the previous implementation where I could potentially make three calls just to find the correct redis key, now it's only makes one call for the index list.

**Pull request merged**
